export const projects = [
  {
    id: 1,
    title: "Blogora",
    description: "Modern blogging platform with rich content editing",
    imgUrl: "/Images/blogora.png",
    siteUrl: "https://blogorablogs.vercel.app/",
    githubUrl: "https://github.com/muhammadsherazsandila/Bloging-website",
    tags: ["MERN", "CMS", "Authentication"],
    category: "Blogging",
    featured: true,
  },
  {
    id: 2,
    title: "Khushi Riders",
    description: "Professional car rental and travel services website",
    imgUrl: "/Images/khushiriders.png",
    siteUrl: "https://khushiriders.com/",
    githubUrl: "https://github.com/muhammadsherazsandila/khushiriders",
    tags: ["Next.js", "React", "Bootstrap", "SEO"],
    category: "Business",
    featured: false,
  },
  {
    id: 3,
    title: "Sandila Digix",
    description:
      "Digital marketing agency website offering branding, SEO, and social media services",
    imgUrl: "/Images/sandiladigix.png",
    siteUrl: "https://sandiladigix.com/",
    githubUrl: "https://github.com/muhammadsherazsandila",
    tags: ["Next.js", "React", "Tailwind", "SEO", "Marketing"],
    category: "Agency",
    featured: true,
  },
  {
    id: 4,
    title: "Roomify",
    description: "Real-time chat application with user authentication",
    imgUrl: "/Images/roomify.png",
    siteUrl: "https://roomifychat.vercel.app/",
    githubUrl: "https://github.com/muhammadsherazsandila/Chat-room",
    tags: ["MERN", "Socket.IO", "Real-time"],
    category: "Chat",
    featured: false,
  },
  {
    id: 5,
    title: "Trendora",
    description:
      "Modern e-commerce platform with a responsive UI, product cart system, and smooth user experience",
    imgUrl: "/Images/trendora.png",
    siteUrl: "https://trendorashop.vercel.app/",
    githubUrl: "https://github.com/muhammadsherazsandila/Shopping-Cart-System",
    tags: ["E-commerce", "React", "Cart"],
    category: "E-commerce",
    featured: true,
  },
  {
    id: 6,
    title: "Future Programmers",
    description: "Educational platform for aspiring developers",
    imgUrl: "/Images/futureProgrammers.png",
    siteUrl: "https://future-programmers.vercel.app/",
    githubUrl: "https://github.com/muhammadsherazsandila/Future-Programmers",
    tags: ["EJS", "MongoDB", "UI/UX"],
    category: "Education",
    featured: false,
  },
];
